Repository OliDesu/MoBiPa, pull requests merged in 2021-03, with the labels that each got.

#45 [FEAT] l'utilisateur est au courant quand sa course est prise en charge
  app/lib/homes/home_driver.dart
  app/lib/homes/home_passenger.dart
Labels: Backend, Frontend

#47 [FEAT] Interface passager course acceptée faite
  app/android/app/src/main/AndroidManifest.xml
  app/lib/Models/firebaseRequest.dart
  app/lib/homes/home_passenger.dart
  app/lib/homes/interfaces/myRequest.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: Frontend

#51 [FEAT] Recadrage de la photo de profil lors du register
  app/android/app/src/main/AndroidManifest.xml
  app/lib/register_page.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: Frontend

#57 [FEAT] Déconnexion possible depuis les home
  app/lib/homes/home_driver.dart
  app/lib/homes/home_passenger.dart
Labels: Frontend

#60 [FEAT] interface conducteur pendant le trajet
  app/lib/homes/interfaces/doRequest.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: Frontend

#61 Ft fixer bords
  app/lib/homes/home_driver.dart
  app/lib/homes/home_passenger.dart
Labels: Frontend

#65 63 retour reu
  app/lib/homes/home_passenger.dart
  app/lib/homes/interfaces/doRequest.dart
  app/lib/homes/interfaces/myRequest.dart
Labels: Frontend

#68 [FEAT] Interface passager de prise en charge avec confirmation de sa part
  app/lib/homes/interfaces/doRequest.dart
  app/lib/homes/interfaces/myRequest.dart
Labels: Frontend

#70 Nettoyage code + ajout de secrets pour api
  app/.gitignore
  app/lib/Models/keys.dart
  app/lib/homes/home_driver.dart
  app/lib/homes/home_passenger.dart
  app/lib/homes/interfaces/doRequest.dart
  app/lib/homes/interfaces/myRequest.dart
  app/lib/main.dart
  app/lib/register_page.dart
  app/lib/signin_page.dart
  app/pubspec.yaml
  app/test/widget_test.dart
Labels: enhancement

#71 [FIX] plus de problème de retour lors de la déconnexion
  app/.gitignore
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/android/gradle.properties
  app/lib/homes/home_driver.dart
  app/lib/homes/home_passenger.dart
  app/lib/main.dart
Labels: bug
