Repository OliDesu/MoBiPa, pull requests merged in 2021-02, with the labels that each got.

#13 Ajout d'une interface d'acceuil après s'être connecté pour les utilis…
  app/lib/homes/home_driver.dart
  app/lib/homes/home_passenger.dart
  app/lib/signin_page.dart
  app/pubspec.lock
Labels: Frontend

#14 8-Ajout de cartes trello, juste la base
  app/lib/Models/trelloBoard.dart
  app/lib/Models/trelloCard.dart
  app/lib/Models/trelloClient.dart
  app/lib/Models/trelloLabel.dart
  app/lib/Models/trelloList.dart
  app/lib/Models/user.dart
  app/lib/Models/utilisateur.dart
  app/lib/Models/utilisateurRepository.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: Backend

#20 [BACKEND] Cartes trello finies pour un utilisateur
  app/lib/Models/request.dart
  app/lib/Models/user.dart
  app/lib/Models/utilisateur.dart
  app/lib/Models/utilisateurRepository.dart
  app/lib/register_page.dart
  app/lib/signin_page.dart
Labels: Backend

#22 Un utilisateur peut maintenant s'inscrire avec plus d'informations
  app/lib/register_page.dart
  app/pubspec.lock
Labels: Backend, Frontend

#24 [FEAT] Possibilité d'ajouter une photo de profil à l'inscription
  app/lib/register_page.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: Backend, Frontend

#34 [FEAT] On peut créer un compte conducteur désormais
  app/lib/register_page.dart
Labels: Backend, Frontend

#36 [BACK] driver.dart ajouté dans le back et les champs peuvent être accédés
  app/lib/Models/driver.dart
  app/lib/Models/request.dart
  app/lib/Models/trelloBoard.dart
  app/lib/Models/trelloCard.dart
  app/lib/Models/trelloClient.dart
  app/lib/Models/trelloLabel.dart
  app/lib/Models/trelloList.dart
  app/lib/Models/user.dart
  app/lib/Models/utilisateurRepository.dart
Labels: Backend

#38 37 autogen id course
  app/lib/Models/driverRepository.dart
  app/lib/Models/firebaseRequest.dart
  app/lib/Models/user.dart
  app/lib/Models/utilisateurRepository.dart
  app/lib/homes/home_driver.dart
  app/lib/homes/home_passenger.dart
  app/lib/main.dart
  app/lib/signin_page.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: Backend

#41 Tmp will
  app/android/app/src/main/AndroidManifest.xml
  app/lib/Models/firebaseRequest.dart
  app/lib/homes/home_driver.dart
  app/lib/homes/home_passenger.dart
  app/pubspec.lock
  app/test/widget_test.dart
Labels: Backend, Frontend
